name: Debug Builds

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Debug
        run: cargo build

      - name: Archive Artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p target/artifacts
          cp target/debug/marsho-cli target/artifacts/marsho-cli-${{ matrix.os }}-debug

      - name: Archive Windows Artifact
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p target/artifacts
          cp target/debug/marsho-cli.exe target/artifacts/marsho-cli-windows-debug.exe

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-debug
          path: target/artifacts/
