name: Debug Builds

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: aarch64-linux-android
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Install macOS Dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

      - name: Install Android OpenSSL
        if: matrix.target == 'aarch64-linux-android'
        run: |
          git clone https://github.com/KDAB/android_openssl.git
          cd android_openssl
          ./build.sh arm64
          echo "OPENSSL_DIR=$PWD/android_openssl_arm64" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$PWD/android_openssl_arm64/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$PWD/android_openssl_arm64/lib" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Android NDK
        if: matrix.target == 'aarch64-linux-android'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV

      - name: Setup Android target
        if: matrix.target == 'aarch64-linux-android'
        run: |
          rustup target add aarch64-linux-android
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV

      - name: Build Debug
        run: cargo build --target ${{ matrix.target }}

      - name: Archive Artifacts
        if: matrix.target != 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p target/artifacts
          cp target/${{ matrix.target }}/debug/marsho-cli target/artifacts/marsho-cli-${{ matrix.target }}-debug

      - name: Archive Windows Artifact
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p target/artifacts
          cp target/${{ matrix.target }}/debug/marsho-cli.exe target/artifacts/marsho-cli-windows-debug.exe

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-debug
          path: target/artifacts/
