name: Rust Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: aarch64-linux-android
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Install macOS Dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

      - name: Install Android NDK
        if: matrix.target == 'aarch64-linux-android'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Setup Android target
        if: matrix.target == 'aarch64-linux-android'
        run: |
          rustup target add aarch64-linux-android
          echo "ANDROID_NDK_HOME=${{ env.ANDROID_NDK_PATH }}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${{ env.ANDROID_NDK_PATH }}" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=${{ env.ANDROID_NDK_PATH }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV

      - name: Install Android OpenSSL
        if: matrix.target == 'aarch64-linux-android'
        run: |
          # 下载并解压 OpenSSL 源码
          curl -LO https://www.openssl.org/source/openssl-3.1.4.tar.gz
          tar xf openssl-3.1.4.tar.gz
          cd openssl-3.1.4

          # 设置交叉编译环境变量
          export ANDROID_NDK_ROOT=${{ env.ANDROID_NDK_PATH }}
          export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export ANDROID_API=24
          export CC=aarch64-linux-android$ANDROID_API-clang
          export CXX=aarch64-linux-android$ANDROID_API-clang++
          export CFLAGS="-D__ANDROID_API__=$ANDROID_API"
          
          # 配置并编译 OpenSSL
          ./Configure android-arm64 \
            --prefix=$PWD/../openssl-android-arm64 \
            --openssldir=$PWD/../openssl-android-arm64 \
            no-shared no-tests
          
          make -j$(nproc)
          make install_sw

          # 设置环境变量
          echo "OPENSSL_DIR=$PWD/../openssl-android-arm64" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$PWD/../openssl-android-arm64/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$PWD/../openssl-android-arm64/lib" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        shell: bash
        if: matrix.os != 'windows-latest'
        run: |
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --target ${{ matrix.target }}
          fi

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          if ("${{ startsWith(github.ref, 'refs/tags/') }}" -eq "true") {
            cargo build --release --target ${{ matrix.target }}
          } else {
            cargo build --target ${{ matrix.target }}
          }

      - name: Archive Non-Windows Artifacts
        if: matrix.target != 'x86_64-pc-windows-msvc'
        shell: bash
        run: |
          mkdir -p target/artifacts
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            cp target/${{ matrix.target }}/release/marsho-cli target/artifacts/marsho-cli-${{ matrix.target }}
          else
            cp target/${{ matrix.target }}/debug/marsho-cli target/artifacts/marsho-cli-${{ matrix.target }}-debug
          fi

      - name: Archive Windows Artifacts
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path target/artifacts
          if ("${{ startsWith(github.ref, 'refs/tags/') }}" -eq "true") {
            Copy-Item -Path "target/${{ matrix.target }}/release/marsho-cli.exe" -Destination "target/artifacts/marsho-cli-windows.exe"
          } else {
            Copy-Item -Path "target/${{ matrix.target }}/debug/marsho-cli.exe" -Destination "target/artifacts/marsho-cli-windows-debug.exe"
          }

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ startsWith(github.ref, 'refs/tags/') && 'release' || 'debug' }}
          path: target/artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
