name: Release Builds

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Archive Artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p target/artifacts
          cp target/release/marsho-cli target/artifacts/${{ matrix.os }}-binary

      - name: Archive Windows Artifact
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p target/artifacts
          cp target/release/marsho-cli.exe target/artifacts/windows-binary.exe

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-release
          path: target/artifacts/
