name: Release Builds

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: aarch64-linux-android
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Android NDK
        if: matrix.target == 'aarch64-linux-android'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV

      - name: Setup Android target
        if: matrix.target == 'aarch64-linux-android'
        run: |
          rustup target add aarch64-linux-android
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive Artifacts
        if: matrix.target != 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p target/artifacts
          cp target/${{ matrix.target }}/release/marsho-cli target/artifacts/marsho-cli-${{ matrix.target }}

      - name: Archive Windows Artifact
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p target/artifacts
          cp target/${{ matrix.target }}/release/marsho-cli.exe target/artifacts/marsho-cli-windows.exe

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-release
          path: target/artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
